FROM debian:bullseye

MAINTAINER Leandro Ramos <leandroramos@disroot.org>

ENV BACULA_VERSION 11.0.5

# get your key on: https://www.bacula.org/bacula-binary-package-download/
ENV BACULA_KEY 61cf096a918f8

ENV EMAIL leandroramos@disroot.org
